apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
    prometheus.io/scrape: 'true'
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      initContainers:
      - name: mount-world
        image: 'busybox:1.28'
        command: ['sh']
        args:
        - '-c'
        - |
          cp /configmap/config.json /world/config.json
          chmod 777 /world/config.json
        volumeMounts:
        - name: worlds  
          mountPath: /world
        - name: settings
          mountPath: /configmap
      containers:
        - image: 'ryshe/terraria:{{ .Values.image.tag }}'
          name: {{ .Release.Name }}
          imagePullPolicy: Always
          args:
          - "-world"
          - "/root/.local/share/Terraria/Worlds/{{ .Values.terraria.worldName }}.wld"
          - "-autocreate"
          - "{{ .Values.terraria.worldSize }}" 
          ports:
            - name: server
              containerPort: 7777
              protocol: TCP
            - name: http
              containerPort: 7878
              protocol: TCP
          resources:
            limits:
              cpu: {{ .Values.pod.resources.cpu.limit }}
              memory: {{ .Values.pod.resources.memory.limit }}
            requests:
              cpu: {{ .Values.pod.resources.cpu.request }}
              memory: {{ .Values.pod.resources.memory.request }}
          volumeMounts:
            - name: worlds
              mountPath: /root/.local/share/Terraria/Worlds
      volumes:
        - name: settings
          configMap:
            name: {{ .Release.Name }}-configmap
        - name: worlds
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-worlds-claim
