apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
    prometheus.io/scrape: 'true'
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/terraria: {{ include (print $.Template.BasePath "/terraria-server-configmap.yaml") . | sha256sum }}
        checksum/tshock: {{ include (print $.Template.BasePath "/tshock-configmap.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      initContainers:
      - name: mount-world
        image: 'busybox:1.28'
        command: ['sh']
        args:
        - '-c'
        - |
          \cp /terraria-server-settings/config.json /world/config.json
          \cp /tshock-settings/sscconfig.json /world/sscconfig.json
          chmod 777 /world/config.json
          chmod 777 /world/sscconfig.json
          echo "{{ .Values.terraria.motd }}" > /world/motd.txt
        volumeMounts:
        - name: worlds  
          mountPath: /world
        - name: terraria-server-settings
          mountPath: /terraria-server-settings
        - name: tshock-settings
          mountPath: /tshock-settings
      containers:
        - image: 'ryshe/terraria:{{ .Values.image.tag }}'
          name: {{ .Release.Name }}
          imagePullPolicy: Always
          tty: {{ .Values.pod.isTtyEnabled }}
          stdin: {{ .Values.pod.isStdinEnabled }}
          args:
          - "-worldname"
          - "{{ .Values.terraria.worldName }}"
          - "-world"
          - "/root/.local/share/Terraria/Worlds/{{ .Values.terraria.worldName }}.wld"
          - "-autocreate"
          - "{{ .Values.terraria.worldSize }}" 
          ports:
            - name: server
              containerPort: 7777
              protocol: TCP
            - name: http
              containerPort: 7878
              protocol: TCP
          resources:
            limits:
              cpu: {{ .Values.pod.resources.cpu.limit }}
              memory: {{ .Values.pod.resources.memory.limit }}
            requests:
              cpu: {{ .Values.pod.resources.cpu.request }}
              memory: {{ .Values.pod.resources.memory.request }}
          volumeMounts:
            - name: worlds
              mountPath: /root/.local/share/Terraria/Worlds
      volumes:
        - name: terraria-server-settings
          configMap:
            name: {{ .Release.Name }}-terraria-server-configmap
        - name: tshock-settings
          configMap:
            name: {{ .Release.Name }}-tshock-configmap
        - name: worlds
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-worlds-claim
