apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
    prometheus.io/scrape: 'true'
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - image: 'ryshe/terraria:{{ .Values.image.tag }}'
          name: {{ .Release.Name }}
          tty: {{ .Values.pod.isTtyEnabled }}
          stdin: {{ .Values.pod.isStdinEnabled }}
          imagePullPolicy: Always
          args:
          - "-killinactivesocket"
          - "-autocreate"
          - "{{ .Values.terraria.worldSize }}" 
          - "-world"
          - "/root/.local/share/Terraria/Worlds/{{ .Values.terraria.worldName }}.wld"
          ports:
            - name: server
              containerPort: 7777
              protocol: TCP
            - name: http
              containerPort: 7878
              protocol: TCP
          resources:
            limits:
              cpu: {{ .Values.pod.resources.cpu.limit }}
              memory: {{ .Values.pod.resources.memory.limit }}
            requests:
              cpu: {{ .Values.pod.resources.cpu.request }}
              memory: {{ .Values.pod.resources.memory.request }}
          volumeMounts:
            - name: worlds
              mountPath: /root/.local/share/Terraria/Worlds
      securityContext:
        fsGroup: 2000
        runAsUser: 1000
      volumes:
        - name: settings
          configMap:
            name: {{ .Release.Name }}-configmap
        - name: worlds
          persistentVolumeClaim:
            claimName: terraria-worlds
