{{ if .Values.rest.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rest
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 32416
      port: 7878
      protocol: TCP
      targetPort: http
  selector:
    app: {{ .Release.Name  }}
{{- end }}