apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-terraria-server-configmap
  namespace: {{ .Release.Namespace }}
data:
  config.json: |
{{- if .Values.terraria.settings }}
{{ toJson .Values.terraria.settings | indent 4 }}
{{- end }}