apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-tshock-configmap
  namespace: {{ .Release.Namespace }}
data:
  sscconfig.json: |
{{- if .Values.tshock.ssc }}
{{ toJson .Values.tshock.ssc | indent 4 }}
{{- end }}